// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchHub.Services.Backends.Data;

#nullable disable

namespace TwitchHub.Migrations
{
    [DbContext(typeof(PointsDbContext))]
    partial class PointsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TwitchHub.Services.Backends.Entities.UserPoints", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("UserId");

                    b.ToTable("UserPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
